-- Corrige a coluna id_projeto (PK de "NotasDeCortes") quando ela perdeu o
-- atributo IDENTITY/sequence — artefato comum de dump/restore "manual" (ex.:
-- exportar via CSV/script em vez de pg_dump -Fc), que não preserva a
-- definição de IDENTITY da coluna nem a sequence associada.
--
-- Foi assim que achamos esse bug no banco local (dump feito a partir do
-- dev/Supabase): id_projeto veio NULL em todas as linhas importadas de
-- 2026, e o TypeORM colapsava várias linhas com PK NULL em uma só ao
-- hidratar a entidade — só 1 de 9 modalidades aparecia na tela de
-- Detalhes. Como o local foi dumpado do dev, é possível (mas não certo)
-- que o mesmo problema exista lá — por isso o diagnóstico abaixo, ANTES
-- de aplicar qualquer coisa.
--
-- 1) DIAGNÓSTICO — rode isso primeiro, não altera nada:
--
-- SELECT
--   (SELECT COUNT(*) FROM "NotasDeCortes" WHERE id_projeto IS NULL) AS linhas_com_id_nulo,
--   is_nullable,
--   column_default
-- FROM information_schema.columns
-- WHERE table_name = 'NotasDeCortes' AND column_name = 'id_projeto';
--
-- Se "linhas_com_id_nulo" for 0 E "column_default" já mostrar algo como
-- nextval(...) (ou is_nullable = 'NO' com identity configurada), o banco
-- já está bom — NÃO precisa rodar o resto deste script.
--
-- Se vier linhas com id_projeto NULL, ou column_default vazio/NULL com
-- is_nullable = 'YES', é o mesmo problema do local. Rode o restante abaixo.

-- 2) Preenche os id_projeto NULL com valores únicos, continuando a partir
--    do maior id_projeto já existente (idempotente: se não houver NULL,
--    o UPDATE não afeta nenhuma linha).
DO $$
DECLARE
  maior_id integer;
BEGIN
  SELECT COALESCE(MAX(id_projeto), 0) INTO maior_id FROM "NotasDeCortes";

  WITH linhas_nulas AS (
    SELECT ctid, ROW_NUMBER() OVER () AS posicao
    FROM "NotasDeCortes"
    WHERE id_projeto IS NULL
  )
  UPDATE "NotasDeCortes" n
  SET id_projeto = maior_id + linhas_nulas.posicao
  FROM linhas_nulas
  WHERE n.ctid = linhas_nulas.ctid;
END $$;

-- 3) Garante NOT NULL na coluna (pré-requisito pra virar chave de identity).
ALTER TABLE "NotasDeCortes" ALTER COLUMN id_projeto SET NOT NULL;

-- 4) Adiciona GENERATED BY DEFAULT AS IDENTITY só se a coluna ainda não
--    tiver uma (evita erro "column already has an identity" se rodar de
--    novo por engano, ou se o ambiente já estiver correto).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_attribute
    WHERE attrelid = '"NotasDeCortes"'::regclass
      AND attname = 'id_projeto'
      AND attidentity <> ''
  ) THEN
    ALTER TABLE "NotasDeCortes" ALTER COLUMN id_projeto ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- 5) Sincroniza a sequence com o maior id_projeto já usado — sem isso, a
--    sequence pode começar do 1 de novo e colidir com IDs já existentes
--    na próxima inserção.
SELECT setval(
  pg_get_serial_sequence('"NotasDeCortes"', 'id_projeto'),
  (SELECT MAX(id_projeto) FROM "NotasDeCortes")
);
